name: Build And Test C# Console App

on:
  push:
    branches: [ "master", "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --verbosity normal

  publish:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish for Windows
        run: >
          dotnet publish github-actions-demo.ConsoleApp/github-actions-demo.ConsoleApp.csproj 
          --configuration Release 
          --runtime win-x64 
          --output ./publish
          -p:PublishSingleFile=true
          -p:IncludeNativeLibrariesForSelfExtract=true

      - name: Archive the executable
        run: Compress-Archive -Path ./publish/github-actions-demo.ConsoleApp.exe -DestinationPath github-actions-demo.ConsoleApp-Windows.zip

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: github-actions-demo.ConsoleApp-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
